data:
  location_files:
    - path: ./data/cities.json
      cls: City
    - path: ./data/terminals.json
      cls: Terminal
  connection_files:
    - path: ./data/car_connections.json
      cls: CarConnection
    - path: ./data/ferry_connections.json
      cls: FerryConnection
